project(u)
set(${PROJECT_NAME}_VENDOR "uael")
set(${PROJECT_NAME}_CONTACT "github.com/uael/mu/issues")
set(${PROJECT_NAME}_SUMMARY "libu - μ c cross-platform multi purpose library")
set(${PROJECT_NAME}_MAJOR 0)
set(${PROJECT_NAME}_MINOR 1)
set(${PROJECT_NAME}_PATCH 0)
set(${PROJECT_NAME}_README README.md)
set(${PROJECT_NAME}_LICENSE LICENSE)